export const data = [
  {
    id: 1,
    name: "iphone 12",
    color: "white",
    price: 49000,
    category: "electronics",
    rating: 4.5,
    stock: 4000,
  },
  {
    id: 2,
    name: "Nike Air",
    color: "black",
    price: 5200,
    category: "shoes",
    rating: 4.2,
    stock: 1200,
  },
  {
    id: 3,
    name: "Puma Tshirt",
    color: "white",
    price: 1200,
    category: "clothing",
    rating: 4.0,
    stock: 1800,
  },
  {
    id: 4,
    name: "Taj Tea",
    color: "black",
    price: 600,
    category: "groceries",
    rating: 4.1,
    stock: 8000,
  },
  {
    id: 5,
    name: "Redmi LED TV",
    color: "blue",
    price: 12000,
    category: "electronics",
    rating: 3.5,
    stock: 4200,
  },
  {
    id: 6,
    name: "Oppo Enco Buds",
    color: "blue",
    price: 2000,
    category: "electronics",
    rating: 3.9,
    stock: 3280,
  },
  {
    id: 7,
    name: "Wildcraft Backpack",
    color: "red",
    price: 3200,
    category: "travel",
    rating: 3.7,
    stock: 4110,
  },
  {
    id: 8,
    name: "ring",
    color: "white",
    price: 200,
    category: "accesories",
    rating: 2.0,
    stock: 400,
  },
  {
    id: 9,
    name: "iphone 13",
    color: "black",
    price: 59000,
    category: "electronics",
    rating: 4.5,
    stock: 800,
  },
  {
    id: 10,
    name: "MacBook Pro",
    color: "white",
    price: 159000,
    category: "electronics",
    rating: 4.57,
    stock: 1100,
  },
  {
    id: 11,
    name: "Tuar Dal",
    color: "yellow",
    price: 120,
    category: "groceries",
    rating: 4.0,
    stock: 4000,
  },
  {
    id: 12,
    name: "Macaroni",
    color: "white",
    price: 220,
    category: "groceries",
    rating: 3.9,
    stock: 1750,
  },
  {
    id: 13,
    name: "Cereals",
    color: "brown",
    price: 360,
    category: "groceries",
    rating: 4.1,
    stock: 1900,
  },
  {
    id: 14,
    name: "Key Chain",
    color: "yellow",
    price: 200,
    category: "accesories",
    rating: 4.1,
    stock: 200,
  },
];
