export const data = [
  {
    id: 1,
    name: "iphone12",
    color: "white",
    price: 49000,
    category: "electronics",
    rating: 4.5,
  },
  {
    id: 2,
    name: "Nike Air",
    color: "black",
    price: 5200,
    category: "shoes",
    rating: 4.2,
  },
  {
    id: 3,
    name: "Puma Tshirt",
    color: "white",
    price: 1200,
    category: "clothing",
    rating: 4.0,
  },
  {
    id: 4,
    name: "Taj Tea",
    color: "black",
    price: 600,
    category: "groceries",
    rating: 4.1,
  },
  {
    id: 5,
    name: "Redmi LED TV",
    color: "blue",
    price: 12000,
    category: "electronics",
    rating: 3.5,
  },
  {
    id: 6,
    name: "Oppo Enco Buds",
    color: "blue",
    price: 2000,
    category: "electronics",
    rating: 3.9,
  },
  {
    id: 7,
    name: "Wildcraft Backpack",
    color: "red",
    price: 3200,
    category: "travel",
    rating: 3.7,
  },
  {
    id: 8,
    name: "ring",
    color: "white",
    price: 200,
    category: "accesories",
    rating: 2.0,
  },
  {
    id: 9,
    name: "iphone13",
    color: "black",
    price: 59000,
    category: "electronics",
    rating: 4.5,
  },
];
